<?xml version="1.0" encoding="UTF-8"?>
<Layout version="1.6.1">
  <Mode>Vertical</Mode>
  <X>1257</X>
  <Y>549</Y>
  <VerticalWidth>229</VerticalWidth>
  <VerticalHeight>248</VerticalHeight>
  <HorizontalWidth>-1</HorizontalWidth>
  <HorizontalHeight>-1</HorizontalHeight>
  <Settings>
    <TextColor>FFFFFFFF</TextColor>
    <BackgroundColor>FF0D0D0D</BackgroundColor>
    <BackgroundColor2>FF282828</BackgroundColor2>
    <ThinSeparatorsColor>03FFFFFF</ThinSeparatorsColor>
    <SeparatorsColor>FF2A302A</SeparatorsColor>
    <PersonalBestColor>FF16A6FF</PersonalBestColor>
    <AheadGainingTimeColor>FF00CC36</AheadGainingTimeColor>
    <AheadLosingTimeColor>FF52CC73</AheadLosingTimeColor>
    <BehindGainingTimeColor>FFCC5C52</BehindGainingTimeColor>
    <BehindLosingTimeColor>FFCC1200</BehindLosingTimeColor>
    <BestSegmentColor>FFD8AF1F</BestSegmentColor>
    <UseRainbowColor>False</UseRainbowColor>
    <NotRunningColor>FFACACAC</NotRunningColor>
    <PausedColor>FF7A7A7A</PausedColor>
    <TextOutlineColor>00000000</TextOutlineColor>
    <ShadowsColor>80000000</ShadowsColor>
    <TimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAQEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAABAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></TimesFont>
    <TimerFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAdDYWxpYnJpAAAvQgX8////GFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQEAAAAHdmFsdWVfXwAIAgAAAAEAAAAF+////xtTeXN0ZW0uRHJhd2luZy5HcmFwaGljc1VuaXQBAAAAB3ZhbHVlX18ACAIAAAACAAAACw==]]></TimerFont>
    <TextFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAQEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></TextFont>
    <AlwaysOnTop>True</AlwaysOnTop>
    <ShowBestSegments>True</ShowBestSegments>
    <AntiAliasing>False</AntiAliasing>
    <DropShadows>False</DropShadows>
    <BackgroundType>HorizontalGradient</BackgroundType>
    <BackgroundImage />
    <ImageOpacity>1</ImageOpacity>
    <ImageBlur>0</ImageBlur>
    <Opacity>1</Opacity>
  </Settings>
  <Components>
    <Component>
      <Path>LiveSplit.Title.dll</Path>
      <Settings>
        <Version>1.7</Version>
        <ShowGameName>True</ShowGameName>
        <ShowCategoryName>True</ShowCategoryName>
        <ShowAttemptCount>False</ShowAttemptCount>
        <ShowFinishedRunsCount>False</ShowFinishedRunsCount>
        <OverrideTitleFont>False</OverrideTitleFont>
        <OverrideTitleColor>False</OverrideTitleColor>
        <TitleFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAUEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAgAAAAs=]]></TitleFont>
        <CenterTitle>False</CenterTitle>
        <SingleLine>True</SingleLine>
        <TitleColor>FFFFFFFF</TitleColor>
        <BackgroundColor>FF3E3E3E</BackgroundColor>
        <BackgroundColor2>FF343434</BackgroundColor2>
        <BackgroundGradient>Vertical</BackgroundGradient>
        <DisplayGameIcon>True</DisplayGameIcon>
        <ShowRegion>False</ShowRegion>
        <ShowPlatform>False</ShowPlatform>
        <ShowVariables>True</ShowVariables>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Splits.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <CurrentSplitTopColor>FF07233F</CurrentSplitTopColor>
        <CurrentSplitBottomColor>FF0E487E</CurrentSplitBottomColor>
        <VisualSplitCount>9</VisualSplitCount>
        <SplitPreviewCount>1</SplitPreviewCount>
        <DisplayIcons>True</DisplayIcons>
        <ShowThinSeparators>False</ShowThinSeparators>
        <AlwaysShowLastSplit>True</AlwaysShowLastSplit>
        <SplitWidth>20</SplitWidth>
        <SplitTimesAccuracy>Seconds</SplitTimesAccuracy>
        <AutomaticAbbreviations>False</AutomaticAbbreviations>
        <BeforeNamesColor>FFFFFFFF</BeforeNamesColor>
        <CurrentNamesColor>FFFFFFFF</CurrentNamesColor>
        <AfterNamesColor>FFFFFFFF</AfterNamesColor>
        <OverrideTextColor>False</OverrideTextColor>
        <BeforeTimesColor>FFFFFFFF</BeforeTimesColor>
        <CurrentTimesColor>FFFFFFFF</CurrentTimesColor>
        <AfterTimesColor>FFFFFFFF</AfterTimesColor>
        <OverrideTimesColor>False</OverrideTimesColor>
        <ShowBlankSplits>False</ShowBlankSplits>
        <LockLastSplit>True</LockLastSplit>
        <IconSize>24</IconSize>
        <IconShadows>True</IconShadows>
        <SplitHeight>0</SplitHeight>
        <CurrentSplitGradient>Horizontal</CurrentSplitGradient>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>01FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <SeparatorLastSplit>True</SeparatorLastSplit>
        <DeltasAccuracy>Tenths</DeltasAccuracy>
        <DropDecimals>True</DropDecimals>
        <OverrideDeltasColor>False</OverrideDeltasColor>
        <DeltasColor>FFFFFFFF</DeltasColor>
        <Display2Rows>False</Display2Rows>
        <ShowColumnLabels>False</ShowColumnLabels>
        <LabelsColor>FFFFFFFF</LabelsColor>
        <Columns>
          <Settings>
            <Version>1.5</Version>
            <Name>Time</Name>
            <Type>DeltaorSplitTime</Type>
            <Comparison>Current Comparison</Comparison>
            <TimingMethod>Current Timing Method</TimingMethod>
          </Settings>
        </Columns>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Timer.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <TimerHeight>69</TimerHeight>
        <TimerWidth>225</TimerWidth>
        <TimerFormat>1.23</TimerFormat>
        <OverrideSplitColors>True</OverrideSplitColors>
        <ShowGradient>False</ShowGradient>
        <TimerColor>FFADFF2F</TimerColor>
        <BackgroundColor>FF243108</BackgroundColor>
        <BackgroundColor2>FF486210</BackgroundColor2>
        <BackgroundGradient>Horizontal</BackgroundGradient>
        <CenterTimer>False</CenterTimer>
        <TimingMethod>Current Timing Method</TimingMethod>
        <DecimalsSize>35</DecimalsSize>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.PreviousSegment.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <BackgroundColor>FF1C201C</BackgroundColor>
        <BackgroundColor2>FF394039</BackgroundColor2>
        <BackgroundGradient>Horizontal</BackgroundGradient>
        <DeltaAccuracy>Tenths</DeltaAccuracy>
        <DropDecimals>True</DropDecimals>
        <Comparison>Current Comparison</Comparison>
        <Display2Rows>False</Display2Rows>
        <ShowPossibleTimeSave>False</ShowPossibleTimeSave>
        <TimeSaveAccuracy>Tenths</TimeSaveAccuracy>
      </Settings>
    </Component>
  </Components>
</Layout>