pub const PADDING: f32 = 0.35;
pub const BOTH_PADDINGS: f32 = 2.0 * PADDING;
const BOTH_VERTICAL_PADDINGS: f32 = DEFAULT_COMPONENT_HEIGHT - DEFAULT_TEXT_ASCENT_DESCENT_DISTANCE;
const VERTICAL_PADDING: f32 = BOTH_VERTICAL_PADDINGS / 2.0;
const ICON_MIN_VERTICAL_PADDING: f32 = 0.1;
pub const DEFAULT_COMPONENT_HEIGHT: f32 = 1.0;
pub const TWO_ROW_HEIGHT: f32 = 2.0 * DEFAULT_TEXT_ASCENT_DESCENT_DISTANCE + BOTH_VERTICAL_PADDINGS;
pub const DEFAULT_TEXT_SIZE: f32 = 0.6;
const DEFAULT_TEXT_ASCENT: f32 = 0.55;
const DEFAULT_TEXT_DESCENT: f32 = 0.175;
const DEFAULT_TEXT_ASCENT_DESCENT_DISTANCE: f32 = DEFAULT_TEXT_ASCENT + DEFAULT_TEXT_DESCENT;
pub const TEXT_ALIGN_TOP: f32 = VERTICAL_PADDING + DEFAULT_TEXT_ASCENT;
pub const TEXT_ALIGN_BOTTOM: f32 = -(VERTICAL_PADDING + DEFAULT_TEXT_DESCENT);
pub const TEXT_ALIGN_CENTER: f32 = DEFAULT_TEXT_ASCENT - DEFAULT_TEXT_ASCENT_DESCENT_DISTANCE / 2.0;
pub const SEPARATOR_THICKNESS: f32 = 0.1;
pub const THIN_SEPARATOR_THICKNESS: f32 = SEPARATOR_THICKNESS / 2.0;
pub const PSEUDO_PIXELS: f32 = 1.0 / 24.0;
pub const DEFAULT_VERTICAL_WIDTH: f32 = 11.5;

pub fn vertical_padding(height: f32) -> f32 {
    (ICON_MIN_VERTICAL_PADDING * height).min(PADDING)
}
